import React from "react";
import Head from "next/head";
export default function forgotpass() {
  return (
    <>
      <Head>
        <title>provast work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white">
        <div className="sm:mx-auto sm:w-full sm:max-w-md w-[300px] mx-auto mt-28 bg-white">
          <form className="bg-white shadow-md rounded-lg px-12 pt-20 pb-12 mb-4 sm:mx-auto sm:w-full">
            {/* <div className='sm:mx-auto sm:w-full sm:max-w-md'> */}

            <h1 className="text-center font-bold text-4xl text-black">
              Forgot Password
            </h1>
            <div className="mb-4 mt-10">
              <label
                className="block text-gray-700 text-sm mb-2 font-semibold"
                htmlFor="username"
              >
                Email address
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-2 focus:ring-orange-500 "
                id="username"
                name="email"
                type="email"
              />
            </div>
            <div className="text-center mt-5">
              <input
                type="submit"
                value="Submit Email Address"
                className="bg-orange-600 font-semibold cursor-pointer block w-[100%] text-white h-10 rounded-md hover:bg-orange-700"
              />
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
