import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>provast work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='text-red-500'>lets do it</h1>

        <form action="./api/register" method='POST'>

          <input type="email"  placeholder='email' name="email" className='border-black'/>
          <input type="password"  placeholder='password' name="password" className='border-black'/>
          <input type="submit" value="click" />
        </form>
        <Link href="/sakshi">sakshi</Link>
        <Link href="/sighnup">skt</Link>
      </main>
    </>
  )
}
