import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
export default function sakshi() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
    <img
          className="w-screen h-screen"
          src="https://qsf.fs.quoracdn.net/-4-ans_frontend_assets.images.home_page_bg_desktop.png-26-4770753d59b970e1.png"
          alt=""
        />
    </main>
  </>
  )
}
